//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Online_Assessment
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Project_Online_AssessmentEntities : DbContext
    {
        public Project_Online_AssessmentEntities()
            : base("name=Project_Online_AssessmentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Difficulty_table> Difficulty_table { get; set; }
        public DbSet<Gender_table> Gender_table { get; set; }
        public DbSet<Option_table> Option_table { get; set; }
        public DbSet<Question_mapping_table> Question_mapping_table { get; set; }
        public DbSet<Question_table> Question_table { get; set; }
        public DbSet<Subject_table> Subject_table { get; set; }
        public DbSet<Test_mapping_table> Test_mapping_table { get; set; }
        public DbSet<Test_result_table> Test_result_table { get; set; }
        public DbSet<Test_table> Test_table { get; set; }
        public DbSet<User_table> User_table { get; set; }
    }
}
