//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Online_Assessment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test_table
    {
        public Test_table()
        {
            this.Question_mapping_table = new HashSet<Question_mapping_table>();
            this.Test_mapping_table = new HashSet<Test_mapping_table>();
            this.Test_result_table = new HashSet<Test_result_table>();
        }
    
        public int Test_id { get; set; }
        public int Subject_Id { get; set; }
        public int No_of_questions { get; set; }
        public int Difficulty_Id { get; set; }
    
        public virtual Difficulty_table Difficulty_table { get; set; }
        public virtual ICollection<Question_mapping_table> Question_mapping_table { get; set; }
        public virtual Subject_table Subject_table { get; set; }
        public virtual ICollection<Test_mapping_table> Test_mapping_table { get; set; }
        public virtual ICollection<Test_result_table> Test_result_table { get; set; }
    }
}
