//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Online_Assessment
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_table
    {
        public User_table()
        {
            this.Test_mapping_table = new HashSet<Test_mapping_table>();
            this.Test_result_table = new HashSet<Test_result_table>();
        }
    
        public int User_Id { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Confirm_Password { get; set; }
        public string Mobile { get; set; }
        public int Age { get; set; }
        public int Gender { get; set; }
    
        public virtual ICollection<Test_mapping_table> Test_mapping_table { get; set; }
        public virtual ICollection<Test_result_table> Test_result_table { get; set; }
    }
}
